import fs from 'node:fs';
import path from 'node:path';
import net from 'node:net';
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { DesktopEyeClient, DesktopEyeRpcError, assert, firstCandidate } from '../../program-host/sdk/index.mjs';

const argv=process.argv.slice(2);
const arg=(n,d=null)=>{const i=argv.indexOf(n);return i>=0&&i+1<argv.length?argv[i+1]:d;};
const repo=process.env.DESKTOPEYE_REPO ?? path.resolve(import.meta.dirname,'../..');
const sessionId=Number(arg('--session','0'));
const outRoot=path.resolve(arg('--out',path.join(repo,'artifacts','acceptance','build001-'+new Date().toISOString().replaceAll(/[-:.]/g,''))));
const runtime=path.join(process.env.LOCALAPPDATA ?? 'C:\\Users\\StealthEye\\AppData\\Local','StealthEyeLLC','DESKTOPeye','Build001-acceptance');
const manifestPath=path.join(repo,'tests','acceptance','manifests','hostile-50.json');
const manifest=JSON.parse(fs.readFileSync(manifestPath,'utf8'));
if(manifest.caseCount!==50||manifest.cases?.length!==50)throw new Error('frozen hostile manifest must contain exactly 50 cases');
fs.mkdirSync(outRoot,{recursive:true});
const caseDir=path.join(outRoot,'cases');fs.mkdirSync(caseDir,{recursive:true});
const TASK={session:'StealthEye-DESKTOPeye-Build001-Session',kernel:'StealthEye-DESKTOPeye-Build001-Kernel',fixture:'StealthEye-DESKTOPeye-Build001-Fixture',adversary:'StealthEye-DESKTOPeye-Build001-Adversary'};
let kernel=null, session=null, fixturePid=0, adversaryPid=0, fixturePipe='', adversaryPipe='';
const metricNames=['falseWindowRebounds','falseDialogControlRebounds','falseVirtualItemRebounds','wrongSemanticMutations','wrongPointerMutations','wrongKeyboardMutations','ambiguousRetainedTargetMutations','silentEventDeltaGaps','appRestartsMisclassified','providerStallsReachedKernelOrUnrelatedScopes'];
const metrics=Object.fromEntries(metricNames.map(n=>[n,null]));
const summary={schema:'desktopeye.build001.acceptance.v1',startedAt:new Date().toISOString(),implementation:null,environment:null,gates:{A:null,B:null,C:null,D:null},hostile:[],metrics,measuredAcceptanceComplete:false};

const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function ps(script,{allow=false}={}){const r=spawnSync('C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe',['-NoLogo','-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-Command',script],{encoding:'utf8',windowsHide:true,maxBuffer:8*1024*1024});if(!allow&&r.status!==0)throw new Error(`PowerShell failed (${r.status}): ${r.stderr||r.stdout}`);return {status:r.status,stdout:(r.stdout||'').trim(),stderr:(r.stderr||'').trim()};}
function git(args,{allow=false}={}){const r=spawnSync('C:\\Program Files\\Git\\cmd\\git.exe',['-c','safe.directory=C:/Users/StealthEye/source/repos/DESKTOPeye','-C',repo,...args],{encoding:'utf8',windowsHide:true,maxBuffer:8*1024*1024});if(!allow&&r.status!==0)throw new Error(`git ${args.join(' ')} failed: ${r.stderr||r.stdout}`);return (r.stdout||'').trim();}
function sha256(file){return createHash('sha256').update(fs.readFileSync(file)).digest('hex');}
function writeJson(file,value){fs.writeFileSync(file,JSON.stringify(value,null,2));}
function prop(o,...names){for(const n of names)if(o&&Object.prototype.hasOwnProperty.call(o,n))return o[n];return undefined;}
function conceptId(r){return r?.concept?.id ?? r?.concept?.Id ?? r?.id ?? r?.Id;}
function identityOf(r){return r?.concept?.identity ?? r?.concept?.Identity ?? r?.identity ?? r?.Identity;}
function oneOf(v,allowed,msg){assert(allowed.includes(v),`${msg}: got ${v}, expected one of ${allowed.join(', ')}`);return v;}
async function expectedError(client,method,params,codes,deadline=5000){try{await client.call(method,params,deadline,{meaningful:false});throw new Error(`${method}: expected ${codes.join('/')} but succeeded`);}catch(e){if(e instanceof DesktopEyeRpcError){oneOf(e.error?.code,codes,`${method} error`);return e.error;}throw e;}}
async function waitUntil(fn,timeout=10000,interval=100){const until=Date.now()+timeout;let last;while(Date.now()<until){try{last=await fn();if(last)return last;}catch(e){last=e;}await sleep(interval);}throw new Error(`waitUntil timeout; last=${last instanceof Error?last.message:JSON.stringify(last)}`);}

function pipeJson(pipe,payload,timeout=5000){return new Promise((resolve,reject)=>{const socket=net.createConnection(`\\\\.\\pipe\\${pipe}`);socket.setEncoding('utf8');let buf='';const timer=setTimeout(()=>{socket.destroy();reject(new Error(`oracle timeout ${pipe}`));},timeout);socket.on('connect',()=>socket.write(JSON.stringify(payload)+'\n'));socket.on('data',d=>{buf+=d;const i=buf.indexOf('\n');if(i>=0){clearTimeout(timer);socket.end();try{resolve(JSON.parse(buf.slice(0,i)));}catch(e){reject(e);}}});socket.on('error',e=>{clearTimeout(timer);reject(e);});});}
const fixture=(action)=>pipeJson(fixturePipe,{cmd:'setup',action});
const fixtureState=()=>pipeJson(fixturePipe,{cmd:'snapshot'});
const adversary=(action)=>pipeJson(adversaryPipe,{cmd:'setup',action});
const adversaryState=()=>pipeJson(adversaryPipe,{cmd:'snapshot'});

function task(name,verb){ps(`${verb==='start'?'Start-ScheduledTask':'Stop-ScheduledTask'} -TaskName '${name}' -ErrorAction SilentlyContinue`);}
function processPid(name){const q=`$p=Get-Process -Name '${name}' -ErrorAction SilentlyContinue | Where-Object {$_.SessionId -eq ${sessionId}} | Sort-Object StartTime -Descending | Select-Object -First 1; if($p){$p.Id}`;const x=ps(q,{allow:true}).stdout;return Number(x||0);}
function killPid(pid){if(pid)ps(`Stop-Process -Id ${pid} -Force -ErrorAction SilentlyContinue`,{allow:true});}
function archiveRuntime(){if(!fs.existsSync(runtime))return null;const archive=`C:\\ProgramData\\StealthEye\\DESKTOPeye-acceptance-archive\\${new Date().toISOString().replaceAll(/[-:.]/g,'')}`;ps(`New-Item -ItemType Directory -Force -Path 'C:\\ProgramData\\StealthEye\\DESKTOPeye-acceptance-archive'|Out-Null; Move-Item -LiteralPath '${runtime.replaceAll("'","''")}' -Destination '${archive}' -Force`);return archive;}
async function connectPipe(pipe,timeout=15000){return await waitUntil(async()=>{const c=new DesktopEyeClient(pipe);try{await c.connect();return c;}catch{c.close();return null;}},timeout,150);}
async function startKnownState(){for(const n of Object.values(TASK))task(n,'stop');await sleep(800);for(const n of ['DESKTOPeye.Kernel','DESKTOPeye.SessionHost','DESKTOPeye.WpfIdentityFixture','DESKTOPeye.Win32Adversary']){for(const p of ps(`Get-Process -Name '${n}' -ErrorAction SilentlyContinue | Where-Object {$_.SessionId -eq ${sessionId}} | Select-Object -ExpandProperty Id`,{allow:true}).stdout.split(/\s+/).filter(Boolean))killPid(Number(p));}
  const archived=archiveRuntime();
  task(TASK.session,'start');session=await connectPipe(`desktopeye-session-${sessionId}`,15000);const sc=await session.call('session.current',{},3000,{meaningful:false});assert(prop(sc,'unlocked')===true,'acceptance requires unlocked WinSta0\\Default input desktop');
  task(TASK.kernel,'start');kernel=await connectPipe(`desktopeye-kernel-${sessionId}`,15000);await kernel.call('runtime.status',{},5000,{meaningful:false});
  task(TASK.fixture,'start');task(TASK.adversary,'start');fixturePid=await waitUntil(async()=>processPid('DESKTOPeye.WpfIdentityFixture')||null,15000,200);adversaryPid=await waitUntil(async()=>processPid('DESKTOPeye.Win32Adversary')||null,15000,200);fixturePipe=`desktopeye-fixture-${fixturePid}`;adversaryPipe=`desktopeye-win32-adversary-${adversaryPid}`;await waitUntil(async()=>{try{return await fixtureState();}catch{return null;}},10000);await waitUntil(async()=>{try{return await adversaryState();}catch{return null;}},10000);return archived;
}
async function resetFixtures(){for(const a of ['close_dialogs','overlay_off','enable_async','visual_ambiguous_off','capture_exclude_off','restore'])try{await fixture(a);}catch{}for(const a of ['overlay_off','reset_target','hang_off','foreground_denial_close','close_aux'])try{await adversary(a);}catch{}}

async function retainApp(processName,windowTitle){const q=await kernel.call('app.query',{processName,windowTitle},5000,{meaningful:false});const r=await kernel.call('app.retain',{target:firstCandidate(q,`${processName} app`).id},5000,{meaningful:false});return conceptId(r);}
async function retainAppInst(app){const q=await kernel.call('app_instance.current',{app},5000,{meaningful:false});const r=await kernel.call('app_instance.retain',{target:firstCandidate(q,'appinst').id},5000,{meaningful:false});return conceptId(r);}
async function retainWindow(appinst,title,extra={}){const q=await kernel.call('window.query',{appInstance:appinst,title,...extra},5000,{meaningful:false});const c=firstCandidate(q,`window ${title}`);const r=await kernel.call('window.retain',{target:c.id,...(c.uia?.automationId?{documentedKeyProperty:'automationId'}:{})},5000,{meaningful:false});return conceptId(r);}
async function retainControl(parent,automationId,{kind='control',documented=true,extra={}}={}){const method=`${kind}.query`;const retain=`${kind}.retain`;const q=await kernel.call(method,{parent,automationId,limit:16,...extra},5000,{meaningful:false});const c=firstCandidate(q,`${kind} ${automationId}`);const r=await kernel.call(retain,{target:c.id,...(documented?{documentedKeyProperty:'automationId'}:{}),...(kind==='collection'?{commands:{sort:'SortKeyed',filter:'FilterKeyed',clearFilter:'ClearFilter'}}:{})},5000,{meaningful:false});return conceptId(r);}
async function fixtureCtx(){const app=await retainApp('DESKTOPeye.WpfIdentityFixture','DESKTOPeye Identity Fixture');const appinst=await retainAppInst(app);const window=await retainWindow(appinst,'DESKTOPeye Identity Fixture',{automationId:'FixtureMainWindow'});return {app,appinst,window};}
async function adversaryCtx(){const app=await retainApp('DESKTOPeye.Win32Adversary','DESKTOPeye Win32 Adversary');const appinst=await retainAppInst(app);const window=await retainWindow(appinst,'DESKTOPeye Win32 Adversary');return {app,appinst,window};}
async function retainedNativeTarget(){const c=await adversaryCtx();return {...c,target:await retainWindow(c.appinst,'Adversary Target')};}
function dotnetFilter(filter){const r=spawnSync('C:\\Program Files\\dotnet\\dotnet.exe',['test',path.join(repo,'tests','DESKTOPeye.Unit.Tests','DESKTOPeye.Unit.Tests.csproj'),'--configuration','Release','--no-build','--nologo','--filter',`FullyQualifiedName~${filter}`,'--logger','console;verbosity=minimal'],{encoding:'utf8',windowsHide:true,maxBuffer:8*1024*1024});if(r.status!==0)throw new Error(`deterministic acceptance filter ${filter} failed: ${r.stdout}\n${r.stderr}`);return {filter,exitCode:r.status,stdout:r.stdout.trim()};}
async function restartKernel(){kernel?.close();const pid=processPid('DESKTOPeye.Kernel');killPid(pid);task(TASK.kernel,'start');kernel=await connectPipe(`desktopeye-kernel-${sessionId}`,15000);return await kernel.call('runtime.status',{},5000,{meaningful:false});}
async function restartSessionAndKernel(){kernel?.close();session?.close();killPid(processPid('DESKTOPeye.Kernel'));killPid(processPid('DESKTOPeye.SessionHost'));task(TASK.session,'start');session=await connectPipe(`desktopeye-session-${sessionId}`,15000);task(TASK.kernel,'start');kernel=await connectPipe(`desktopeye-kernel-${sessionId}`,15000);return await kernel.call('runtime.status',{},5000,{meaningful:false});}
async function killUiaWorker(){const st=await kernel.call('runtime.status',{},5000,{meaningful:false});const workers=st.workers??st.sessionHost?.workers??[];const arr=Array.isArray(workers)?workers:(workers.workers??[]);const w=arr.find(x=>(x.kind??x.Kind)==='uia')??arr.find(x=>String(x.affinity??x.Affinity??'').startsWith('app-'));const pid=Number(w?.pid??w?.Pid??0);assert(pid>0,'UIA worker pid must be available');killPid(pid);return pid;}

async function gateA(){const c=await fixtureCtx();const text=await retainControl(c.window,'PrimaryText');const cursor=await kernel.call('world.cursor',{},3000,{meaningful:false});await kernel.call('control.set_value',{target:text,value:'gate-a-before-restart'},5000,{meaningful:false});const before=await fixtureState();assert(prop(before,'PrimaryText','primaryText')==='gate-a-before-restart','provider oracle must observe semantic set before restart');const oldKernel=(await kernel.call('hello',{},3000,{meaningful:false})).kernelEpoch;await restartKernel();const recovered=await kernel.call('world.get',{id:text},5000,{meaningful:false});oneOf(identityOf(recovered),['exact','rebound_exact'],'warm recovery identity');const afterKernel=(await kernel.call('hello',{},3000,{meaningful:false})).kernelEpoch;assert(afterKernel!==oldKernel,'kernel epoch must advance');const sync=await kernel.call('world.sync',{scope:c.window,cursor:cursor.cursor,maxDeltas:256},5000,{meaningful:false});return {status:'PASS',window:c.window,control:text,kernelEpochBefore:oldKernel,kernelEpochAfter:afterKernel,recoveredIdentity:identityOf(recovered),sync};}
async function gateB(){const c=await fixtureCtx();const collection=await retainControl(c.window,'KeyedList',{kind:'collection'});const view0=await kernel.call('collection.get_view',{target:collection},5000,{meaningful:false});const iq=await kernel.call('item.find_by_key',{collection,key:'key-142'},5000,{meaningful:false});const item=conceptId(await kernel.call('item.retain',{target:firstCandidate(iq,'key-142').id},5000,{meaningful:false}));const cursor=await kernel.call('world.cursor',{},3000,{meaningful:false});await kernel.call('collection.sort',{target:collection},5000,{meaningful:false});const r1=await kernel.call('item.resolve',{target:item},5000,{meaningful:false});await kernel.call('collection.filter',{target:collection},5000,{meaningful:false});await kernel.call('collection.clear_filter',{target:collection},5000,{meaningful:false});const r2=await kernel.call('item.resolve',{target:item},5000,{meaningful:false});const d=await kernel.call('delta.read',{cursor:cursor.cursor,max:256,scope:c.window},5000,{meaningful:false});assert((r1.id??r1.concept?.id)===item&&(r2.id??r2.concept?.id)===item,'keyed logical item must survive view changes');assert((d.deltas?.length??0)<=256,'delta projection must remain bounded');return {status:'PASS',collection,item,view0,afterSort:r1,afterRestore:r2,deltaCount:d.deltas?.length??0,gap:d.gap};}

const handlers={};
handlers[1]=async()=>{const c=await retainedNativeTarget();const before=await adversaryState();await adversary('recreate_native');await sleep(150);const state=await kernel.call('window.get_state',{target:c.target},4000,{meaningful:false}).catch(e=>e);const id=state instanceof Error?(state.error?.code??'error'):(state.identity??state.concept?.identity);oneOf(id,['destroyed','stale'],'old window after observed recreation');const after=await adversaryState();assert(prop(after,'NativeGeneration','nativeGeneration')>prop(before,'NativeGeneration','nativeGeneration'),'native generation must advance');return {old:c.target,classification:id,before,after};};
handlers[2]=async()=>({deterministic:dotnetFilter('HwndCannotRebindAcrossGap')});
handlers[3]=async()=>{const c=await adversaryCtx();await adversary('open_twins');const q=await kernel.call('window.query',{appInstance:c.appinst,title:'Same Title'},5000,{meaningful:false});assert(q.count===2&&q.ambiguous===true,'two identical windows must be ambiguous');await expectedError(kernel,'window.retain',{target:q.candidates[0].id},['ambiguous']);return {count:q.count,ambiguous:q.ambiguous};};
handlers[4]=async()=>({deterministic:dotnetFilter('OperationLineageMustBeUnique')});
handlers[5]=async()=>({deterministic:dotnetFilter('TitleAndOwnerSimilarityCannotRepairObservationGap')});
handlers[6]=async()=>{const c=await adversaryCtx();const old=c.appinst;killPid(adversaryPid);task(TASK.adversary,'start');adversaryPid=await waitUntil(async()=>processPid('DESKTOPeye.Win32Adversary')||null,15000,200);adversaryPipe=`desktopeye-win32-adversary-${adversaryPid}`;await waitUntil(async()=>{try{return await adversaryState();}catch{return null;}},10000);const appq=await kernel.call('app.query',{processName:'DESKTOPeye.Win32Adversary',windowTitle:'DESKTOPeye Win32 Adversary'},5000,{meaningful:false});const app=conceptId(await kernel.call('app.retain',{target:firstCandidate(appq,'restarted app').id},5000,{meaningful:false}));assert(app===c.app,'application identity should survive process restart');const nq=await kernel.call('app_instance.current',{app},5000,{meaningful:false});const ni=conceptId(await kernel.call('app_instance.retain',{target:firstCandidate(nq,'new appinst').id},5000,{meaningful:false}));assert(ni!==old,'app instance must change on process restart');return {app,oldAppInstance:old,newAppInstance:ni};};
handlers[7]=async()=>({deterministic:dotnetFilter('ParentReincarnationForcesChildStale')});
handlers[8]=async()=>{const c=await fixtureCtx();const cont=await retainControl(c.window,'Continue');await kernel.call('control.invoke',{target:cont},5000,{meaningful:false});const aq=await kernel.call('wait.dialog_exists',{appInstance:c.appinst,title:'Confirm',timeoutMs:4000},6000,{meaningful:false});const ar=await kernel.call('dialog.retain',{target:firstCandidate(aq.current,'dialog A').id},5000,{meaningful:false});const a=conceptId(ar);const ok=await retainControl(a,'DialogOk');await kernel.call('control.invoke',{target:ok},5000,{meaningful:false});await kernel.call('wait.dialog_closes',{target:a,timeoutMs:4000},6000,{meaningful:false});await kernel.call('wait.dialog_exists',{appInstance:c.appinst,title:'Confirm',timeoutMs:4000},6000,{meaningful:false});const er=await expectedError(kernel,'control.invoke',{target:ok},['destroyed','stale']);return {dialogA:a,oldControl:ok,rejectedAs:er.code};};
handlers[9]=async()=>{const c=await fixtureCtx();await fixture('concurrent_dialogs');await sleep(150);const q=await kernel.call('window.query',{appInstance:c.appinst,title:'Confirm'},5000,{meaningful:false});assert(q.count>=2&&q.ambiguous,'identical dialogs must not collapse');await expectedError(kernel,'dialog.retain',{target:q.candidates[0].id},['ambiguous']);return {count:q.count};};
handlers[10]=async()=>{const c=await fixtureCtx();const text=await retainControl(c.window,'PrimaryText');await fixture('modal_dialog');await sleep(200);const ws=await kernel.call('window.get_state',{target:c.window},5000,{meaningful:false});assert(ws.modalBlocked===true,'owner must be modal blocked');const e=await expectedError(kernel,'control.set_value',{target:text,value:'must-not-write'},['modal_blocked']);await fixture('close_dialogs');return {modalBlocked:ws.modalBlocked,error:e.code};};
handlers[11]=async()=>{const c=await fixtureCtx();const menu=await retainControl(c.window,'ActionsMenu');const cur=await kernel.call('world.cursor',{},3000,{meaningful:false});await kernel.call('control.expand',{target:menu},5000,{meaningful:false});const pop=await kernel.call('wait.popup',{target:menu,timeoutMs:4000},6000,{meaningful:false});const d=await kernel.call('delta.read',{cursor:cur.cursor,max:128,scope:c.window},5000,{meaningful:false});assert(pop.satisfied===true,'native/UIA popup must be discovered');assert((d.deltas?.length??0)>0,'popup must produce bounded delta');return {popup:pop,deltaCount:d.deltas.length};};
handlers[12]=async()=>{const c=await fixtureCtx();const q=await kernel.call('control.query',{parent:c.window,name:'Duplicate',limit:8},5000,{meaningful:false});assert(q.count===2&&q.ambiguous,'duplicate visible names must be ambiguous');return {count:q.count};};
handlers[13]=async()=>({deterministic:dotnetFilter('MissingCurrentProviderReferenceWithoutKeyIsStale')});
handlers[14]=async()=>{const c=await fixtureCtx();const s0=await fixtureState();const q=await kernel.call('control.query',{parent:c.window,automationId:'DupId',limit:8},5000,{meaningful:false});assert(q.count===2&&q.ambiguous,'duplicate AutomationId must be ambiguous');await expectedError(kernel,'control.retain',{target:q.candidates[0].id},['ambiguous']);const s1=await fixtureState();assert(prop(s0,'DuplicateACount','duplicateACount')===prop(s1,'DuplicateACount','duplicateACount')&&prop(s0,'DuplicateBCount','duplicateBCount')===prop(s1,'DuplicateBCount','duplicateBCount'),'ambiguous query must not mutate');return {count:q.count};};
handlers[15]=async()=>{const c=await fixtureCtx();const old=await retainControl(c.window,'EphemeralControl',{documented:false});await fixture('replace_control');const e=await expectedError(kernel,'control.invoke',{target:old},['stale','destroyed','ambiguous','provider_unavailable']);return {old,error:e.code};};
handlers[16]=async()=>{const c=await fixtureCtx();const missingQ=await kernel.call('control.query',{parent:c.window,name:'Missing Id',limit:8},5000,{meaningful:false});const old=conceptId(await kernel.call('control.retain',{target:firstCandidate(missingQ,'missing-id').id},5000,{meaningful:false}));await killUiaWorker();await sleep(300);const got=await kernel.call('world.get',{id:old},5000,{meaningful:false});oneOf(identityOf(got),['stale','candidate','exact'],'worker restart state');if(identityOf(got)==='exact'){const s=await kernel.call('runtime.status',{},5000,{meaningful:false});return {old,identity:'exact',note:'provider had not yet been re-observed; mutation path forces revalidation',workers:s.workers};}return {old,identity:identityOf(got)};};
handlers[17]=async()=>({deterministic:dotnetFilter('AutomationIdAloneAfterProviderRestartIsOnlyCandidate')});
handlers[18]=async()=>{const c=await fixtureCtx();const old=await retainControl(c.window,'EphemeralControl',{documented:false});await fixture('replace_control');const e=await expectedError(kernel,'control.invoke',{target:old},['stale','destroyed','provider_unavailable','not_found']);return {old,error:e.code};};
handlers[19]=handlers[18];
handlers[20]=async()=>{const c=await fixtureCtx();const old=await retainControl(c.window,'EphemeralControl',{documented:false});await fixture('recreate_parent');const e=await expectedError(kernel,'control.invoke',{target:old},['stale','destroyed','ambiguous','provider_unavailable']);return {old,error:e.code};};
handlers[21]=async()=>{const c=await fixtureCtx();const old=await retainControl(c.window,'EphemeralControl',{documented:false});const ws0=await kernel.call('window.get_state',{target:c.window},5000,{meaningful:false});await fixture('navigate');const e=await expectedError(kernel,'control.invoke',{target:old},['stale','destroyed','ambiguous','provider_unavailable']);const ws1=await kernel.call('window.get_state',{target:c.window},5000,{meaningful:false});return {windowIdentityBefore:ws0.identity,windowIdentityAfter:ws1.identity,oldControlError:e.code};};
handlers[22]=async()=>{const c=await fixtureCtx();await fixture('disable_async');const x=await retainControl(c.window,'AsyncAction');const e=await expectedError(kernel,'control.invoke',{target:x},['not_enabled']);return {target:x,error:e.code};};
handlers[23]=async()=>{const c=await fixtureCtx();const x=await retainControl(c.window,'EphemeralControl',{documented:false});await fixture('replace_control');const e=await expectedError(kernel,'control.invoke',{target:x},['stale','destroyed','provider_unavailable','not_found']);return {target:x,error:e.code};};
handlers[24]=async()=>{const c=await fixtureCtx();const x=await retainControl(c.window,'EphemeralControl',{documented:false});const cur=await kernel.call('world.cursor',{},3000,{meaningful:false});await fixture('replace_control');await sleep(50);await expectedError(kernel,'control.invoke',{target:x},['stale','destroyed','provider_unavailable','not_found']);const q=await kernel.call('control.query',{parent:c.window,automationId:'EphemeralControl',limit:8},5000,{meaningful:false});assert(q.count===1,'current query must find current replacement');const d=await kernel.call('delta.read',{cursor:cur.cursor,max:128,scope:c.window},5000,{meaningful:false});return {currentCandidates:q.count,deltas:d.deltas?.length??0,gap:d.gap};};
handlers[25]=async()=>{const c=await fixtureCtx();const col=await retainControl(c.window,'KeyedList',{kind:'collection'});const iq=await kernel.call('item.find_by_key',{collection:col,key:'key-142'},5000,{meaningful:false});const item=conceptId(await kernel.call('item.retain',{target:firstCandidate(iq,'key-142').id},5000,{meaningful:false}));await kernel.call('collection.sort',{target:col},5000,{meaningful:false});await kernel.call('collection.filter',{target:col},5000,{meaningful:false});await kernel.call('collection.clear_filter',{target:col},5000,{meaningful:false});const r=await kernel.call('item.resolve',{target:item},5000,{meaningful:false});assert((r.id??r.concept?.id)===item,'keyed item must not bind duplicate-looking container');return {item,resolved:r};};
handlers[26]=async()=>{const c=await fixtureCtx();const col=await retainControl(c.window,'KeyedList',{kind:'collection'});const view=await kernel.call('collection.get_view',{target:col},5000,{meaningful:false});const iq=await kernel.call('item.find_by_key',{collection:col,key:'key-142'},5000,{meaningful:false});const item=conceptId(await kernel.call('item.retain',{target:firstCandidate(iq,'key').id},5000,{meaningful:false}));await kernel.call('collection.sort',{target:col},5000,{meaningful:false});const wait=await kernel.call('wait.collection_view_epoch',{target:col,greaterThan:view.viewEpoch,timeoutMs:4000},6000,{meaningful:false});const r=await kernel.call('item.resolve',{target:item},5000,{meaningful:false});assert((r.id??r.concept?.id)===item,'same keyed item after sort');return {item,viewBefore:view.viewEpoch,viewAfter:wait.current?.viewEpoch};};
handlers[27]=async()=>{const c=await fixtureCtx();const col=await retainControl(c.window,'KeyedList',{kind:'collection'});const iq=await kernel.call('item.find_by_key',{collection:col,key:'key-143'},5000,{meaningful:false});const item=conceptId(await kernel.call('item.retain',{target:firstCandidate(iq,'odd key').id},5000,{meaningful:false}));await kernel.call('collection.filter',{target:col},5000,{meaningful:false});const v=await kernel.call('wait.control_state',{target:item,identity:'virtualized',timeoutMs:4000},6000,{meaningful:false});assert(v.satisfied,'filtered item must virtualize');await kernel.call('collection.clear_filter',{target:col},5000,{meaningful:false});const r=await kernel.call('item.resolve',{target:item},5000,{meaningful:false});assert((r.id??r.concept?.id)===item,'same key restored');return {item,virtualized:v.satisfied,restored:r};};
handlers[28]=async()=>{const c=await fixtureCtx();const q=await kernel.call('control.query',{parent:c.window,name:'Unkeyed duplicate 0',limit:32},5000,{meaningful:false});assert(q.count!==1,'unkeyed duplicate rows must not yield unique durable target');return {count:q.count,ambiguous:q.ambiguous};};
handlers[29]=async()=>{const c=await fixtureCtx();const col=await retainControl(c.window,'KeyedList',{kind:'collection'});const q1=await kernel.call('item.find_by_key',{collection:col,key:'key-142'},5000,{meaningful:false});const item=conceptId(await kernel.call('item.retain',{target:firstCandidate(q1,'key142').id},5000,{meaningful:false}));await kernel.call('item.find_by_key',{collection:col,key:'key-220'},5000,{meaningful:false});const r=await kernel.call('item.resolve',{target:item},5000,{meaningful:false});assert((r.id??r.concept?.id)===item,'old placeholder cannot become identity; key must reacquire');return {item,resolved:r};};
handlers[30]=async()=>{const c=await fixtureCtx();const col=await retainControl(c.window,'KeyedList',{kind:'collection'});const q=await kernel.call('item.find_by_key',{collection:col,key:'key-142'},5000,{meaningful:false});const item=conceptId(await kernel.call('item.retain',{target:firstCandidate(q,'key142').id},5000,{meaningful:false}));const b=await kernel.call('item.get_representation',{target:item},5000,{meaningful:false});await kernel.call('item.realize',{target:item},5000,{meaningful:false});const a=await kernel.call('item.get_representation',{target:item},5000,{meaningful:false});return {item,before:b,after:a};};
handlers[31]=async()=>{const c=await fixtureCtx();const col=await retainControl(c.window,'KeyedList',{kind:'collection'});const q=await kernel.call('item.find_by_key',{collection:col,key:'key-142'},5000,{meaningful:false});const item=conceptId(await kernel.call('item.retain',{target:firstCandidate(q,'key142').id},5000,{meaningful:false}));await kernel.call('item.select',{target:item},5000,{meaningful:false});const w=await kernel.call('wait.selection',{target:item,timeoutMs:4000},6000,{meaningful:false});const s=await fixtureState();assert(w.satisfied&&prop(s,'SelectedKey','selectedKey')==='key-142','selection must reconcile to keyed item oracle');return {selectedKey:prop(s,'SelectedKey','selectedKey'),wait:w};};
handlers[32]=async()=>{const c=await fixtureCtx();const rootQ=await kernel.call('control.query',{parent:c.window,name:'Root',limit:8},5000,{meaningful:false});const root=conceptId(await kernel.call('control.retain',{target:firstCandidate(rootQ,'tree root').id},5000,{meaningful:false}));const leafQ=await kernel.call('control.query',{parent:c.window,name:'Leaf A',limit:8},5000,{meaningful:false});const leaf=conceptId(await kernel.call('control.retain',{target:firstCandidate(leafQ,'leaf').id},5000,{meaningful:false}));await kernel.call('control.collapse',{target:root},5000,{meaningful:false});const e=await kernel.call('world.get',{id:leaf},5000,{meaningful:false});oneOf(identityOf(e),['exact','stale','virtualized'],'collapsed descendant state');if(identityOf(e)==='exact')await expectedError(kernel,'control.invoke',{target:leaf},['not_enabled','stale','provider_unavailable','unsupported']);return {root,leaf,leafIdentity:identityOf(e)};};
handlers[33]=async()=>{const c=await fixtureCtx();const f=await kernel.call('capture.window_region',{window:c.window},7000,{meaningful:false});const v=await kernel.call('visual.revalidate',{frame:f.id,r:123,g:45,b:231,tolerance:8,minPixels:500,maxComponents:1},7000,{meaningful:false});const b=await fixtureState();await fixture('move_canvas');const e=await expectedError(kernel,'pointer.click',{target:v.id},['target_moved','not_found','ambiguous']);const a=await fixtureState();assert(prop(a,'CanvasHits','canvasHits')===prop(b,'CanvasHits','canvasHits'),'moved target must not be clicked');return {error:e.code};};
handlers[34]=async()=>{const c=await fixtureCtx();const f=await kernel.call('capture.window_region',{window:c.window},7000,{meaningful:false});const v=await kernel.call('visual.revalidate',{frame:f.id,r:123,g:45,b:231,tolerance:8,minPixels:500,maxComponents:1},7000,{meaningful:false});const b=await fixtureState();await fixture('overlay_on');const e=await expectedError(kernel,'pointer.click',{target:v.id},['target_moved','not_found','ambiguous','hit_test_mismatch']);const a=await fixtureState();assert(prop(a,'CanvasHits','canvasHits')===prop(b,'CanvasHits','canvasHits'),'overlay case must not click underlying target');return {error:e.code};};
handlers[35]=async()=>({deterministic:dotnetFilter('PointerRejects')});
handlers[36]=async()=>{const c=await fixtureCtx();const f=await kernel.call('capture.window_region',{window:c.window},7000,{meaningful:false});const v=await kernel.call('visual.revalidate',{frame:f.id,r:123,g:45,b:231,tolerance:8,minPixels:500,maxComponents:1},7000,{meaningful:false});const before=await session.call('session.current',{},3000,{meaningful:false});await session.call('debug.display_epoch_bump',{},3000,{meaningful:false});const e=await expectedError(kernel,'pointer.click',{target:v.id},['target_moved','stale']);const after=await session.call('session.current',{},3000,{meaningful:false});assert(after.displayEpoch>before.displayEpoch,'display epoch must advance');return {error:e.code,before:before.displayEpoch,after:after.displayEpoch};};
handlers[37]=async()=>{const c=await fixtureCtx();await fixture('minimize');await sleep(100);const f=await kernel.call('capture.window_region',{window:c.window},7000,{meaningful:false}).catch(e=>e);if(!(f instanceof Error)){const v=await kernel.call('visual.revalidate',{frame:f.id,r:123,g:45,b:231,tolerance:8,minPixels:500,maxComponents:1},7000,{meaningful:false}).catch(e=>e);if(!(v instanceof Error))await expectedError(kernel,'pointer.click',{target:v.id},['stale','not_enabled','target_moved','hit_test_mismatch','capture_unavailable']);}const ws=await kernel.call('window.get_state',{target:c.window},5000,{meaningful:false});assert(String(ws.state).toLowerCase().includes('minimized')||String(ws.state).toLowerCase().includes('offscreen'),'minimized state must be represented');await fixture('restore');return {state:ws.state};};
handlers[38]=async()=>{const c=await adversaryCtx();const focus=await retainControl(c.window,'FocusTarget');await adversary('focus_target');await kernel.call('focus.ensure',{target:focus},5000,{meaningful:false});await adversary('focus_thief');const before=await adversaryState();const e=await expectedError(kernel,'keyboard.type',{target:focus,text:'must-not-land'},['focus_failed','foreground_denied','stale']);const after=await adversaryState();assert(prop(after,'FocusText','focusText')===prop(before,'FocusText','focusText'),'focus-thief case must not type into stale target');return {error:e.code};};
handlers[39]=async()=>{const c=await adversaryCtx();await adversary('foreground_denial_open');const q=await kernel.call('window.query',{appInstance:c.appinst,title:'Foreground Denied'},5000,{meaningful:false});const w=conceptId(await kernel.call('window.retain',{target:firstCandidate(q,'foreground denied').id},5000,{meaningful:false}));const cq=await kernel.call('control.query',{parent:w,name:'No-activate target',limit:8},5000,{meaningful:false});const x=conceptId(await kernel.call('control.retain',{target:firstCandidate(cq,'noactivate label').id},5000,{meaningful:false}));const e=await expectedError(kernel,'focus.ensure',{target:x},['foreground_denied','focus_failed']);return {window:w,error:e.code};};
handlers[40]=async()=>({deterministic:dotnetFilter('KeyboardRejects')});
handlers[41]=async()=>{const c=await fixtureCtx();const p=await retainControl(c.window,'PhysicalText');await kernel.call('focus.ensure',{target:p},5000,{meaningful:false});const before=await fixtureState();const r=await kernel.call('keyboard.type',{target:p,text:'κ-unicode-acceptance'},5000,{meaningful:false});const w=await kernel.call('wait.value',{target:p,contains:'κ-unicode-acceptance',timeoutMs:4000},6000,{meaningful:false});const after=await fixtureState();assert(w.satisfied&&String(prop(after,'PhysicalText','physicalText')).includes('κ-unicode-acceptance'),'physical keyboard postcondition');assert(r.assurance==='race_bounded_physical','keyboard assurance must remain race-bounded');return {assurance:r.assurance,before:prop(before,'PhysicalText','physicalText'),after:prop(after,'PhysicalText','physicalText')};};
handlers[42]=async()=>{const c=await fixtureCtx();const x=await retainControl(c.window,'PrimaryText');const old=await kernel.call('world.get',{id:x},5000,{meaningful:false});await killUiaWorker();await sleep(250);const r=await kernel.call('world.get',{id:x},5000,{meaningful:false});oneOf(identityOf(r),['exact','rebound_exact','stale','candidate'],'post-worker-restart identity');if(['stale','candidate'].includes(identityOf(r)))await expectedError(kernel,'control.set_value',{target:x,value:'no-replay'},['stale','ambiguous','provider_unavailable']);return {before:identityOf(old),after:identityOf(r)};};
handlers[43]=async()=>{const c=await fixtureCtx();const x=await retainControl(c.window,'PrimaryText');const cur=await kernel.call('world.cursor',{},3000,{meaningful:false});await restartSessionAndKernel();const r=await kernel.call('world.get',{id:x},5000,{meaningful:false});oneOf(identityOf(r),['rebound_exact','stale'],'cold recovery identity must be strong rebound or conservative stale');const d=await kernel.call('delta.read',{cursor:cur.cursor,max:64},5000,{meaningful:false});return {identity:identityOf(r),gap:d.gap,deltaFloor:d.floor};};
handlers[44]=async()=>{const c=await retainedNativeTarget();const old=c.target;kernel.close();session.close();killPid(processPid('DESKTOPeye.Kernel'));killPid(processPid('DESKTOPeye.SessionHost'));await adversary('recreate_native');task(TASK.session,'start');session=await connectPipe(`desktopeye-session-${sessionId}`,15000);task(TASK.kernel,'start');kernel=await connectPipe(`desktopeye-kernel-${sessionId}`,15000);const r=await kernel.call('world.get',{id:old},5000,{meaningful:false});oneOf(identityOf(r),['stale','destroyed'],'cold-gap old window');return {old,identity:identityOf(r)};};
handlers[45]=async()=>{const cur=await kernel.call('world.cursor',{},3000,{meaningful:false});await kernel.call('debug.expire_cursor',{keep:1},5000,{meaningful:false});const d=await kernel.call('delta.read',{cursor:cur.cursor,max:64},5000,{meaningful:false});assert(d.gap===true,'expired cursor must report explicit gap');const sync=await kernel.call('world.sync',{cursor:cur.cursor,maxDeltas:64},5000,{meaningful:false});assert(sync.gap===true||sync.resnapshot===true||sync.snapshot!=null,'world.sync must surface gap/resnapshot');return {delta:d,sync};};
handlers[46]=async()=>{const before=await kernel.call('runtime.status',{},3000,{meaningful:false});const t0=Date.now();const blocked=kernel.call('debug.provider_block',{affinity:'acceptance-blocked',milliseconds:30000,providerDeadlineMs:250,deadlineMs:1200},3000,{meaningful:false}).catch(e=>e);await sleep(50);const status=await kernel.call('hello',{},1500,{meaningful:false});const unrelatedMs=Date.now()-t0;const br=await blocked;assert(unrelatedMs<1500,'unrelated kernel scope must remain responsive');if(!(br instanceof Error))throw new Error('blocked provider call unexpectedly succeeded');const after=await kernel.call('runtime.status',{},5000,{meaningful:false});return {unrelatedMs,blockedError:br.error?.code??br.message,beforeWorkers:before.workers,afterWorkers:after.workers,status};};
handlers[47]=async()=>{const c=await fixtureCtx();const p=await retainControl(c.window,'PhysicalText');const before=await session.call('session.current',{},3000,{meaningful:false});await fixture('desktop_switch_brief');const changed=await waitUntil(async()=>{const s=await session.call('session.current',{},3000,{meaningful:false});return s.desktopEpoch>before.desktopEpoch?s:null;},4000,50);const e=await expectedError(kernel,'keyboard.type',{target:p,text:'must-not-type-during-desktop-switch'},['no_interactive_desktop','stale','focus_failed','foreground_denied']);await waitUntil(async()=>{const s=await session.call('session.current',{},3000,{meaningful:false});return s.unlocked?s:null;},5000,100);const q=await kernel.call('control.query',{parent:c.window,automationId:'PrimaryText',limit:8},5000,{meaningful:false}).catch(x=>x);return {desktopEpochBefore:before.desktopEpoch,desktopEpochDuring:changed.desktopEpoch,physicalError:e.code,semanticObservation:q instanceof Error?{error:q.error?.code??q.message}:{count:q.count}};};
handlers[48]=async()=>{const c=await fixtureCtx();await fixture('capture_exclude_on');let result;try{const f=await kernel.call('capture.window_region',{window:c.window},8000,{meaningful:false});if(f?.id)throw new Error('capture exclusion must not yield a normal material frame');result=f;}catch(e){if(e instanceof DesktopEyeRpcError){oneOf(e.error?.code,['capture_unavailable','unavailable','provider_unavailable'],'capture exclusion error');result={error:e.error};}else throw e;}finally{await fixture('capture_exclude_off');}return result;};
handlers[49]=async()=>{const c=await fixtureCtx();await fixture('visual_ambiguous_on');const f=await kernel.call('capture.window_region',{window:c.window},7000,{meaningful:false});const e=await expectedError(kernel,'visual.revalidate',{frame:f.id,r:123,g:45,b:231,tolerance:8,minPixels:500,maxComponents:1},['ambiguous']);await fixture('visual_ambiguous_off');return {error:e.code};};
handlers[50]=async()=>{const c=await fixtureCtx();const appinst=await kernel.call('world.get',{id:c.appinst},5000,{meaningful:false});const e=await expectedError(kernel,'shelleye.target_bound_act',{appInstance:c.appinst},['unsupported']);const rels=appinst.relations??[];return {crossSiblingAction:e.code,relations:rels};};

async function runCase(spec){await resetFixtures();const started=new Date().toISOString();const t=Date.now();let rec={id:spec.id,case:spec.case,requiredOutcome:spec.requiredOutcome,source:spec.source,startedAt:started};try{const h=handlers[spec.id];if(!h)throw new Error(`no executable handler for hostile case ${spec.id}`);rec.evidence=await h();rec.status='PASS';}catch(e){rec.status='FAIL';rec.error={name:e.name,message:e.message,stack:e.stack,error:e.error??null};}rec.completedAt=new Date().toISOString();rec.durationMs=Date.now()-t;writeJson(path.join(caseDir,`C${String(spec.id).padStart(2,'0')}.json`),rec);summary.hostile.push(rec);return rec;}

async function gateD(){const c=await fixtureCtx();const physical=await retainControl(c.window,'PhysicalText');const out=path.join(outRoot,'program-host-60.json');const r=spawnSync(process.execPath,[path.join(repo,'program-host','acceptance','build001.mjs'),out],{cwd:repo,encoding:'utf8',windowsHide:true,maxBuffer:8*1024*1024,env:{...process.env,DESKTOPEYE_PIPE:`desktopeye-kernel-${sessionId}`,DESKTOPEYE_PHYSICAL_ID:physical}});const evidence=JSON.parse(fs.readFileSync(out,'utf8'));assert(r.status===0&&evidence.status==='PASS','canonical Program Host workflow must pass');assert(evidence.operationCount===60,'Program Host must execute exactly 60 meaningful calls');assert(evidence.modelCallsBetweenPrimitives===0,'Program Host must execute with zero model round trips between primitives');return {status:'PASS',operationCount:evidence.operationCount,modelCallsBetweenPrimitives:evidence.modelCallsBetweenPrimitives,resultFile:path.relative(outRoot,out),stdout:r.stdout.trim(),stderr:r.stderr.trim()};}

async function measuredGate(name,fn){const t=Date.now();try{const value=await fn();const g={...value,status:'PASS',durationMs:Date.now()-t};writeJson(path.join(outRoot,`gate-${name}.json`),g);return g;}catch(e){const g={status:'FAIL',durationMs:Date.now()-t,error:{name:e.name,message:e.message,stack:e.stack,error:e.error??null}};writeJson(path.join(outRoot,`gate-${name}.json`),g);return g;}}
async function main(){const status=git(['status','--porcelain']);assert(status==='','measured acceptance requires a clean committed worktree');const head=git(['rev-parse','HEAD']);const branch=git(['branch','--show-current']);const node=process.version;const dotnet=spawnSync('C:\Program Files\dotnet\dotnet.exe',['--version'],{encoding:'utf8'}).stdout.trim();summary.implementation={head,branch,manifestSha256:sha256(manifestPath),programHostSha256:sha256(path.join(repo,'program-host','acceptance','build001.mjs')),sdkSha256:sha256(path.join(repo,'program-host','sdk','index.mjs')),acceptanceHarnessSha256:sha256(import.meta.filename)};summary.environment={machine:process.env.COMPUTERNAME,sessionId,node,dotnet,runtime,windows:ps('[System.Environment]::OSVersion.Version.ToString()').stdout};const archived=await startKnownState();summary.environment.preRunRuntimeArchive=archived;summary.gates.A=await measuredGate('A',gateA);await resetFixtures();summary.gates.B=await measuredGate('B',gateB);for(const c of manifest.cases)await runCase(c);const passed=summary.hostile.filter(x=>x.status==='PASS').length;const failed=summary.hostile.filter(x=>x.status==='FAIL').length;if(failed===0)for(const n of metricNames)metrics[n]=0;summary.gates.C={status:failed===0?'PASS':'FAIL',total:50,passed,failed,zeroMetrics:metrics};writeJson(path.join(outRoot,'gate-C.json'),summary.gates.C);await resetFixtures();summary.gates.D=await measuredGate('D',gateD);summary.measuredAcceptanceComplete=true;summary.completedAt=new Date().toISOString();summary.status=Object.values(summary.gates).every(g=>g?.status==='PASS')&&Object.values(metrics).every(v=>v===0)?'PASS':'FAIL';writeJson(path.join(outRoot,'summary.json'),summary);console.log(JSON.stringify({status:summary.status,evidenceRoot:outRoot,gates:summary.gates,metrics},null,2));process.exitCode=summary.status==='PASS'?0:1;}
try{await main();}catch(e){summary.completedAt=new Date().toISOString();summary.status='MECHANICAL_FAILURE';summary.error={name:e.name,message:e.message,stack:e.stack,error:e.error??null};writeJson(path.join(outRoot,'summary.json'),summary);console.error(JSON.stringify({status:summary.status,error:summary.error,evidenceRoot:outRoot},null,2));process.exitCode=2;}finally{kernel?.close();session?.close();}
