using System.Diagnostics;
using System.IO.Pipes;
using System.Security.Cryptography;
using System.Text.Json;
using DESKTOPeye.Platform.Windows;

namespace DESKTOPeye.Acceptance;

public static class Program
{
    static readonly JsonSerializerOptions Json=new(JsonSerializerDefaults.Web){WriteIndented=true};
    public static async Task<int> Main(string[] args)
    {
        var root=FindRepo();var command=args.FirstOrDefault()?.ToLowerInvariant()??"list";
        try{return command switch{"list"=>List(root),"validate-harness"=>await Validate(root),"preflight"=>Preflight(root,true).Ready?0:2,"run"=>await Run(root),_=>throw new InvalidOperationException("usage: DESKTOPeye.Acceptance [list|validate-harness|preflight|run]")};}
        catch(Exception ex){Console.Error.WriteLine(ex);return 1;}
    }
    static int List(string root){var manifest=ReadManifest(root);Console.WriteLine(JsonSerializer.Serialize(new{count=manifest.Length,cases=manifest},Json));return 0;}
    static async Task<int> Validate(string root)
    {
        var manifest=ReadManifest(root);if(manifest.Length!=50)throw new InvalidOperationException($"hostile manifest must contain 50 cases; got {manifest.Length}");var ids=manifest.Select(x=>x.GetProperty("id").GetInt32()).Order().ToArray();if(!ids.SequenceEqual(Enumerable.Range(1,50)))throw new InvalidOperationException("hostile manifest IDs must be exactly 1..50");
        var node=NodePath();await RunProcess(node,"--check \"program-host/sdk/index.mjs\"",root);await RunProcess(node,"--check \"program-host/acceptance/build001.mjs\"",root);await RunProcess(node,"--check \"program-host/acceptance/hostile50.mjs\"",root);await RunProcess(node,"--check \"program-host/test/noninteractive.mjs\"",root);await RunProcess(node,"\"program-host/test/noninteractive.mjs\"",root);await RunProcess(node,"\"program-host/acceptance/hostile50.mjs\" --classify-only",root);
        Console.WriteLine(JsonSerializer.Serialize(new{status="PASS",hostileCases=50,node=Version(node,"--version"),programHostNoninteractive="PASS",resultsDocumentExists=File.Exists(Path.Combine(root,"docs","09-BUILD-001-RESULTS.md"))},Json));return 0;
    }
    static PreflightResult Preflight(string root,bool print)
    {
        var branch=Git(root,"branch --show-current").Trim();var head=Git(root,"rev-parse HEAD").Trim();var status=Git(root,"status --porcelain");string remote="";try{remote=Git(root,$"rev-parse refs/remotes/origin/{branch}").Trim();}catch{}var sid=Process.GetCurrentProcess().SessionId;var explorers=Process.GetProcessesByName("explorer").Where(p=>p.SessionId==sid).Select(p=>p.Id).ToArray();var station=NativeDesktop.WindowStationName();var desktop=NativeDesktop.InputDesktopName();var ready=Environment.UserInteractive&&sid>0&&explorers.Length>0&&string.Equals(station,"WinSta0",StringComparison.OrdinalIgnoreCase)&&string.Equals(desktop,"Default",StringComparison.OrdinalIgnoreCase)&&branch!="main"&&branch.StartsWith("build/",StringComparison.Ordinal)&&string.IsNullOrWhiteSpace(status)&&head==remote;var r=new PreflightResult(ready,Environment.MachineName,Environment.UserName,sid,Environment.UserInteractive,explorers.Length>0,station,desktop,branch,head,remote,string.IsNullOrWhiteSpace(status));if(print)Console.WriteLine(JsonSerializer.Serialize(new{status=ready?"READY_INTERACTIVE":"BLOCKED_INTERACTIVE",preflight=r,requirement="authenticated interactive StealthEye WinSta0\\Default; clean provider-published development branch"},Json));return r;
    }
    static async Task<int> Run(string root)
    {
        var pre=Preflight(root,true);if(!pre.Ready)throw new InvalidOperationException("measured acceptance refused: interactive/provider freeze preflight is not satisfied");if(File.Exists(Path.Combine(root,"docs","09-BUILD-001-RESULTS.md")))throw new InvalidOperationException("results document already exists; measured run will not overwrite/adapt prior result");
        var stamp=DateTimeOffset.Now.ToString("yyyyMMdd-HHmmss");var evidence=Path.Combine(root,"artifacts","build001-acceptance",stamp);Directory.CreateDirectory(evidence);var runtime=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"StealthEyeLLC","DESKTOPeye","Build001-acceptance-"+stamp);Directory.CreateDirectory(runtime);var sid=pre.SessionId;var sessionPipe=$"desktopeye-session-{sid}-accept-{stamp.Replace("-","")}";var kernelPipe=$"desktopeye-kernel-{sid}-accept-{stamp.Replace("-","")}";var dllBase="net10.0-windows10.0.26100.0";var worker=Path.Combine(root,"src","DESKTOPeye.UIA.Worker","bin","Release",dllBase,"win-x64","DESKTOPeye.UIA.Worker.dll");var sessionDll=Path.Combine(root,"src","DESKTOPeye.SessionHost","bin","Release",dllBase,"win-x64","DESKTOPeye.SessionHost.dll");var kernelDll=Path.Combine(root,"src","DESKTOPeye.Kernel","bin","Release",dllBase,"win-x64","DESKTOPeye.Kernel.dll");var wpfDll=Path.Combine(root,"fixtures","DESKTOPeye.WpfIdentityFixture","bin","Release",dllBase,"win-x64","DESKTOPeye.WpfIdentityFixture.dll");var advDll=Path.Combine(root,"fixtures","DESKTOPeye.Win32Adversary","bin","Release",dllBase,"win-x64","DESKTOPeye.Win32Adversary.dll");foreach(var f in new[]{worker,sessionDll,kernelDll,wpfDll,advDll})if(!File.Exists(f))throw new FileNotFoundException("Build 001 binary missing; run Release build before acceptance",f);
        var freezeFiles=new[]{"docs/01-ARCHITECTURE.md","docs/02-BUILD-001-SLICE.md","program-host/sdk/index.mjs","program-host/acceptance/build001.mjs","program-host/acceptance/hostile50.mjs","tests/acceptance/manifests/hostile-50.json","tests/DESKTOPeye.Acceptance/Program.cs","fixtures/DESKTOPeye.WpfIdentityFixture/MainWindow.xaml.cs","fixtures/DESKTOPeye.Win32Adversary/Program.cs"};var freeze=new{createdAt=DateTimeOffset.Now,gitHead=pre.Head,branch=pre.Branch,machine=pre.Machine,user=pre.User,sessionId=pre.SessionId,windowStation=pre.WindowStation,inputDesktop=pre.InputDesktop,windows=Environment.OSVersion.VersionString,dotnet=Version("dotnet","--version"),node=Version(NodePath(),"--version"),files=freezeFiles.ToDictionary(x=>x,x=>Sha256(Path.Combine(root,x)))};await File.WriteAllTextAsync(Path.Combine(evidence,"implementation-freeze.json"),JsonSerializer.Serialize(freeze,Json));
        var owned=new List<Process>();try
        {
            owned.Add(Start("dotnet",Quote(sessionDll)+$" --pipe {sessionPipe} --runtime "+Quote(runtime)+" --worker-dll "+Quote(worker),root));await WaitPipe(sessionPipe,5000);
            owned.Add(Start("dotnet",Quote(kernelDll)+$" --pipe {kernelPipe} --session-pipe {sessionPipe} --runtime "+Quote(runtime)+" --database "+Quote(Path.Combine(runtime,"world.db")),root));await WaitPipe(kernelPipe,7000);
            var wpf=Start("dotnet",Quote(wpfDll),root);owned.Add(wpf);var adv=Start("dotnet",Quote(advDll),root);owned.Add(adv);await Task.Delay(1500);if(wpf.HasExited||adv.HasExited)throw new InvalidOperationException("fixture process exited during startup");
            var env=new Dictionary<string,string>{{"DESKTOPEYE_KERNEL_PIPE",kernelPipe},{"DESKTOPEYE_WPF_PID",wpf.Id.ToString()},{"DESKTOPEYE_ADV_PID",adv.Id.ToString()},{"DESKTOPEYE_HOSTILE_MANIFEST",Path.Combine(root,"tests","acceptance","manifests","hostile-50.json")}};
            var program=await RunProcessCapture(NodePath(),"\"program-host/acceptance/build001.mjs\"",root,env,Path.Combine(evidence,"program-host-60.json"));var hostile=await RunProcessCapture(NodePath(),"\"program-host/acceptance/hostile50.mjs\"",root,env,Path.Combine(evidence,"hostile-50.json"));var summary=new{status=program==0&&hostile==0?"MEASURED_SUITE_FINISHED":"MEASURED_SUITE_FAILED",implementation=freeze.gitHead,programHostExit=program,hostileExit=hostile,evidenceDirectory=evidence,note="No results document or canonical status promotion is produced by this runner."};await File.WriteAllTextAsync(Path.Combine(evidence,"acceptance-summary.json"),JsonSerializer.Serialize(summary,Json));Console.WriteLine(JsonSerializer.Serialize(summary,Json));return program==0&&hostile==0?0:3;
        }
        finally{foreach(var p in owned.AsEnumerable().Reverse())try{if(!p.HasExited)p.Kill(true);}catch{}}
    }
    static JsonElement[] ReadManifest(string root){var p=Path.Combine(root,"tests","acceptance","manifests","hostile-50.json");if(!File.Exists(p))throw new FileNotFoundException("hostile manifest absent",p);return JsonDocument.Parse(File.ReadAllText(p)).RootElement.EnumerateArray().Select(x=>x.Clone()).ToArray();}
    static string FindRepo(){var d=new DirectoryInfo(AppContext.BaseDirectory);while(d!=null){if(File.Exists(Path.Combine(d.FullName,"DESKTOPeye.slnx")))return d.FullName;d=d.Parent;}var cwd=Directory.GetCurrentDirectory();if(File.Exists(Path.Combine(cwd,"DESKTOPeye.slnx")))return cwd;throw new DirectoryNotFoundException("DESKTOPeye repository root not found");}
    static string NodePath(){var candidates=new[]{Environment.GetEnvironmentVariable("DESKTOPEYE_NODE"),@"C:\AgentBrowser\tools\node-v24.18.1-win-x64\node.exe",@"C:\Program Files\nodejs\node.exe"};return candidates.FirstOrDefault(x=>!string.IsNullOrWhiteSpace(x)&&File.Exists(x))??"node";}
    static string Git(string root,string args)=>Capture("git",args,root);static string Version(string file,string args){try{return Capture(file,args,Directory.GetCurrentDirectory()).Trim();}catch{return"unavailable";}}
    static string Capture(string file,string args,string wd){var p=Process.Start(new ProcessStartInfo(file,args){WorkingDirectory=wd,UseShellExecute=false,RedirectStandardOutput=true,RedirectStandardError=true,CreateNoWindow=true})??throw new InvalidOperationException(file+" failed to start");var stdout=p.StandardOutput.ReadToEnd();var stderr=p.StandardError.ReadToEnd();p.WaitForExit();if(p.ExitCode!=0)throw new InvalidOperationException($"{file} {args} failed ({p.ExitCode}): {stderr}");return stdout;}
    static Process Start(string file,string args,string wd){return Process.Start(new ProcessStartInfo(file,args){WorkingDirectory=wd,UseShellExecute=false,CreateNoWindow=false})??throw new InvalidOperationException(file+" failed to start");}
    static async Task RunProcess(string file,string args,string wd){var rc=await RunProcessCapture(file,args,wd,null,null);if(rc!=0)throw new InvalidOperationException($"{file} {args} failed with {rc}");}
    static async Task<int> RunProcessCapture(string file,string args,string wd,Dictionary<string,string>? env,string? output)
    {
        var psi=new ProcessStartInfo(file,args){WorkingDirectory=wd,UseShellExecute=false,RedirectStandardOutput=true,RedirectStandardError=true,CreateNoWindow=true};if(env!=null)foreach(var (k,v) in env)psi.Environment[k]=v;var p=Process.Start(psi)??throw new InvalidOperationException(file+" failed to start");var stdoutTask=p.StandardOutput.ReadToEndAsync();var stderrTask=p.StandardError.ReadToEndAsync();await p.WaitForExitAsync();var stdout=await stdoutTask;var stderr=await stderrTask;if(output!=null){await File.WriteAllTextAsync(output,stdout);if(!string.IsNullOrWhiteSpace(stderr))await File.WriteAllTextAsync(Path.ChangeExtension(output,".stderr.txt"),stderr);}if(!string.IsNullOrWhiteSpace(stderr))Console.Error.WriteLine(stderr);return p.ExitCode;
    }
    static async Task WaitPipe(string pipe,int timeoutMs){using var cts=new CancellationTokenSource(timeoutMs);while(true){try{await using var p=new NamedPipeClientStream(".",pipe,PipeDirection.InOut,PipeOptions.Asynchronous);await p.ConnectAsync(250,cts.Token);return;}catch when(!cts.IsCancellationRequested){await Task.Delay(50,cts.Token);}}}
    static string Sha256(string path){using var sha=SHA256.Create();using var s=File.OpenRead(path);return Convert.ToHexString(sha.ComputeHash(s)).ToLowerInvariant();}static string Quote(string s)=>'"'+s.Replace("\"","\\\"")+'"';
    sealed record PreflightResult(bool Ready,string Machine,string User,int SessionId,bool UserInteractive,bool ExplorerInSession,string WindowStation,string InputDesktop,string Branch,string Head,string RemoteHead,bool WorkingTreeClean);
}
