<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DESKTOPeye.Protocol\DESKTOPeye.Protocol.csproj" />
    <ProjectReference Include="..\DESKTOPeye.Platform.Windows\DESKTOPeye.Platform.Windows.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
